# Generated by Django 3.2.6 on 2021-08-22 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escola', to='core.endereco', verbose_name='Endereco')),
            ],
        ),
    ]
